// Generated by CoffeeScript 1.6.3
(function() {
  var CORS, app, express;

  express = require('express');

  CORS = require('CORS');

  app = express();

  app.get('/', CORS(require(__dirname + '/config.json')), function(req, res) {
    return res.send('Hello');
  });

  app.listen(3000);

}).call(this);
